### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by aminbabar** [Luckyleck/Tenner#3]
# Database Schema

- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by aminbabar** [comment]
- include time stamps on all tables (created_at, updated_at columns)
- updated_at in gigs table has a typo
- You will need a table for reviews

**Comment by Luckyleck** [comment]
Fixed. About the gig belonging to a user, in this table I'm calling it the seller, but seller is the foreign key that connects user. Users can sell gigs.
