### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by aminbabar** [Luckyleck/Tenner#6]
# Frontend Routes

- [x]  Frontend routes contains wildcard variables written in `camelCase`
- [x]  Correctly formatted
    - [x]  Routes are displayed with inline coding text (backticks)

**Comment by aminbabar** [comment]
- You do not need a route for /home. That would be your /  
- Include details of what components you want to render when you are at a particular route
- You do not need  login and signup routes. Those will just be modals on /

**Comment by Luckyleck** [comment]
Updated
